version: "3.8"
services:
  next:
    build: "./frontend"
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
    ports:
      - "3000:3000"
    depends_on: strapi
    restart: unless-stopped
    volumes:
      - ./app:/srv/app

  strapi:
    build: "./backend"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    ports:
      - "1337:1337"
    depends_on: postgres
    restart: unless-stopped
    volumes:
      - ./app:/srv/app

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
