version: "3.9"
services:
  next:
    container_name: next
    image: ghcr.io/neyroon/noise-studio-frontend:latest
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    restart: unless-stopped

  strapi:
    container_name: strapi
    image: ghcr.io/neyroon/noise-studio-backend:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: ${NODE_ENV}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - backend:/backend/public/uploads

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  backend:
